version: "3"

services:
    activemq:
      image: webcenter/activemq
      ports:
        - 8161:8161
        - 61616:61616
        - 61613:61613
      networks: 
        - turbosonic

    sidecar:
      build: .
      depends_on: 
        - activemq
      ports:
        - 8080:8080
      networks: 
        - turbosonic
      env_file: 
        - .env

networks:
  turbosonic: