name: "CI/CD"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build -t turbosonic/event-hub-sidecar .
    - name: ECR Login
      run: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
      env: 
        DOCKER_USER_NAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker tag
      run: docker tag turbosonic/event-hub-sidecar turbosonic/event-hub-sidecar:latest
    - name: Docker push
      run: docker push turbosonic/event-hub-sidecar:latest